name: Bump Version
on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      ref:
        required: true
        type: string
        default: ${{ github.ref }}
    outputs:
      new_version:
        value: ${{ jobs.bump.outputs.new_version }}
jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.increment_version.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Install semver package
        run: npm i semver

      - name: Increment the Runtime Version
        uses: actions/github-script@v6
        id: increment_version
        env:
          TYPE: ${{ inputs.type }}
        with:
          result-encoding: string
          script: |
            const semver = require('semver');
            const type = process.env.TYPE;
            const output = [];
            const listeners = {
              stdout: (data) => output.push(data.toString()),
              stderr: (data) => console.log("stderr: %s", data)
            };
            await exec.exec("npm", ["pkg", "get", "version"], { listeners });
            console.log("op", output);
            let version = JSON.parse(output.join(""));
            console.log("v", version);
            version = semver.inc(version, type);
            console.log("v", version);
            await exec.exec("npm", ["pkg", "set", `version=${version}`]);
            core.setOutput('new_version', version);

      - name: Updates version.json
        env:
          NEW_VERSION: ${{ steps.increment_version.outputs.new_version }}
        run: node versionUpdate.mjs version ${{ env.NEW_VERSION }}

      - name: Commit Change
        id: commit_version
        uses: EndBug/add-and-commit@v9
        env:
          NEW_VERSION: ${{ steps.increment_version.outputs.new_version }}
        with:
          message: Update version ${{ env.NEW_VERSION }}
          tag: v${{ env.NEW_VERSION }}
          default_author: github_actions
