name: "Update Version"
run-name: Update ${{ github.event.client_payload.service }} to ${{ github.event.client_payload.version }}
on:
  repository_dispatch:
    type: [service_new_version]
env:
  SERVICE: ${{ github.event.client_payload.service }}
  VERSION: ${{ github.event.client_payload.version }}
  TYPE: ${{ github.event.client_payload.type }}
jobs:
  update:
    name: Update `version.json`
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set_branch.outputs.branch }}
    steps:
      - name: Set branch name
        id: set_branch
        run: echo "branch=CI/update/$SERVICE-$VERSION" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Version Update
        run: node versionUpdate.mjs service $SERVICE $VERSION

      - name: Commit Change to New Branch
        id: commit_version
        uses: EndBug/add-and-commit@v9
        with:
          message: Update ${{ env.SERVICE }} to ${{ env.VERSION }} (from GitHub Actions Workflow)
          new_branch: ${{ steps.set_branch.outputs.branch }}
          default_author: github_actions

  call-run-cy-test:
    name: Test
    needs: update
    uses: ./.github/workflows/cy-tests.yml
    with:
      ref: ${{ needs.update.outputs.branch }}

  call-bump-version:
    name: Version
    if: ${{ github.event.client_payload.type == 'minor' || github.event.client_payload.type == 'patch' }}
    needs: [ update, call-run-cy-test ]
    uses: ./.github/workflows/bump-version.yml
    with:
      ref: ${{ needs.update.outputs.branch }}
      # For the runtime, consider service version updates as patch
      type: patch

  merge-release:
    name: Merge & Release
    needs: [ update, call-bump-version ]
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ needs.update.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 5

      - name: Rebase & Merge
        run: | 
          git pull origin master &&
          git checkout master &&
          git checkout ${{ env.BRANCH }} &&
          git rebase master &&
          git checkout master &&
          git merge "${{ env.BRANCH }}" &&
          git push
         
      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.call-bump-version.outputs.new_version }}
          body: ${{ env.SERVICE }} updated to ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Delete branch ${{ env.BRANCH }}
        uses: dawidd6/action-delete-branch@v3
        with:
          branches: ${{ env.BRANCH }}

  fail:
    name: Create a PR
    needs: [ update, call-run-cy-test ]
    if: ${{ failure() || github.event.client_payload.type == 'major' }}
    runs-on: ubuntu-latest
    steps: 
      - name: Get Run URL
        id: run_url
        run: echo "url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v6
        id: my-script
        env:
          BRANCH: ${{ needs.update.outputs.branch }}
          RUN_URL: ${{ steps.run_url.outputs.url }}
        with:
          result-encoding: string
          script: |
            const { SERVICE, VERSION, BRANCH, TYPE, RUN_URL } = process.env;
            const body = TYPE == 'major' ? 'This is a major service update. Automatic updating disabled. Review and merge manually if ready.' : `Automatic updated failed. Check the E2E tests. ${RUN_URL}`;
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Update ${SERVICE} to ${VERSION} (from GitHub Actions Workflow)`,
              base: "master",
              head: BRANCH,
              body,
            });
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: [{name: 'minor'}],
            });
